name: calculadora_anime
description: "Una calculadora de 4 funciones con una chica anime de fondo"
publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  

  math_expressions: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
